mongodb:
  primary:
    uri: mongodb+srv://mkacp:mkacp@cluster0.iecy2.mongodb.net/data?retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000
    database: primary
  secondary:
    uri: mongodb+srv://mkacp:mkacp@cluster1.iecy2.mongodb.net/data?retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000
    database: second